Traceback (most recent call last):
  File "C:\Users\Pedro\AppData\Roaming\Python\Python39\site-packages\satyrus\cli\cli.py", line 315, in run
    answer: tuple[dict, float] | str = sat_api[solver].solve(**params)
  File "C:\Users\Pedro\AppData\Roaming\Python\Python39\site-packages\satyrus\api\api.py", line 171, in __getitem__
    return self.subclasses[key](satyrus=self.satyrus).__solver()
  File "C:\Users\Pedro\AppData\Roaming\Python\Python39\site-packages\satyrus\api\api.py", line 179, in __solver
    self.satyrus.compile()
  File "C:\Users\Pedro\AppData\Roaming\Python\Python39\site-packages\satyrus\satyrus.py", line 51, in compile
    if (self.compiler.compile(Source(fname=self.path))):
  File "C:\Users\Pedro\AppData\Roaming\Python\Python39\site-packages\satyrus\satlib\performance.py", line 29, in timed_callback
    _ = callback(*args, **kwargs)
  File "C:\Users\Pedro\AppData\Roaming\Python\Python39\site-packages\satyrus\compiler\compiler.py", line 178, in compile
    raise error
  File "C:\Users\Pedro\AppData\Roaming\Python\Python39\site-packages\satyrus\compiler\compiler.py", line 165, in compile
    self.execute([CMD_INIT, *BYTECODE, CMD_SCRIPT])
  File "C:\Users\Pedro\AppData\Roaming\Python\Python39\site-packages\satyrus\compiler\compiler.py", line 209, in execute
    self.exec(stmt)
  File "C:\Users\Pedro\AppData\Roaming\Python\Python39\site-packages\satyrus\compiler\compiler.py", line 234, in exec
    return self.instructions[cmd](self, *args)
  File "C:\Users\Pedro\AppData\Roaming\Python\Python39\site-packages\satyrus\compiler\instructions\run_script.py", line 29, in run_script
    run_script_penalties(compiler)
  File "C:\Users\Pedro\AppData\Roaming\Python\Python39\site-packages\satyrus\compiler\instructions\run_script.py", line 76, in run_script_penalties
    constraints = {**compiler.constraints[CONS_OPT], **compiler.constraints[CONS_INT]}
TypeError: 'list' object is not a mapping
